[package]
name = "cogis"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst = "0.15.3"

nalgebra = "0.21.1"
rand_distr = "0.3.0"
rand = "0.7.3"

log = "0.4.11"

#nphysics2d

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
metal = ["amethyst/metal"]
#empty = ["amethyst/empty"]
#nightly = ["amethyst/nightly"]
