[package]
name = "cogis"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst = "0.13"
log = "0.4.8"

[features]
default = ["vulkan"]
vulkan = ["amethyst/vulkan"]
#empty = ["amethyst/empty"]
#metal = ["amethyst/metal"]
#nightly = ["amethyst/nightly"]
